version: '3'

services:

  redis:
    image: redis:5-stretch
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    env_file:
      - .app.env

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    env_file:
      - .app.env

volumes:
  redis: