# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   url: postgresql://demo-database.czq4qlpsbacm.us-west-2.rds.amazonaws.com/my_database?pool=5
#   adapter: postgresql
#   encoding: unicode
#   username: demo_user
#   password: DbPass12345*

default: &default
  adapter: mysql2
  #host: staging-database.cpjx7vbjewe6.us-east-1.rds.amazonaws.com
  host: <%= ENV.fetch('DB_HOST', '') %>
  #port: <%= ENV.fetch('MYSQL_PORT', 3306) %>
  port: 3306
  encoding: utf8mb4
  #username: <%= ENV.fetch('MYSQL_USER', 'staging_user') %>
  username: staging_user
  #password: <%= ENV.fetch('MYSQL_PASSWORD', 'xnA3ccnxQrJPUzxX') %>
  password: xnA3ccnxQrJPUzxX
  collation: utf8mb4_unicode_ci
  #pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  pool: 5
  database: rails-sample

development:
  <<: *default
  #database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  #database: db/production.sqlite3
